### ISSUE TITLE
Implement Outlets

### ISSUE THREAD

**Issue by aleemont1** [progetto-oop-22-23/HOMER#21]
`getConsuption()` and `setConsuption()` methods should be included in Devices' APIs for getting and setting the istant electrical absorption of the devices.

**Comment by aleemont1** [comment]
@michelececcacci @smagnaniuni I was thinking that it might be smarter to implement Outlets with those methods, and then "plug" each device which drains power (e.g. A/C, Lights) to an outlet, but outlets can also be used from devices which are not controlled in the environment (they'd still drain power, so we'll have to think about this, too).

In any case, every powered device should have a range of power consumption as parameters (double minConsumption, double maxConsumption) to be exponed to the Outlet class, which will communicate with the ElectricalMeter.

The meter is going to work as an intermediate layer between outlets and the controller.

Any ideas?

**Comment by smagnaniuni** [comment]
Yes I would model it like that. The controller could then command the outlet and/or the device.

**Comment by aleemont1** [comment]
@michelececcacci any feedback abt this?

**Comment by aleemont1** [comment]
> Yes I would model it like that. The controller could then command the outlet and/or the device.

Yep, the electrical meter will control the outlets only for security reasons (e.g. global consumption is going to break the upper bound or draining from a single device is critical). 

The controller is going to be able to toggle outlets in any moment.
