### ISSUE TITLE
Implement DeviceId

### ISSUE THREAD

**Issue by smagnaniuni** [progetto-oop-22-23/HOMER#27]
@michelececcacci @aleemont1 
A specific type for the device id is clearly required.

A few options:
1. use UUID directly -> `UUID getId()`
2. a `DeviceId` interface that returns an UUID
```java
// this can remain empty, it's just to clearly identify what is a device id
public interface DeviceId extends Supplier<UUID> {}
```
3. a `DeviceId` interface that returns something else
```java
public interface DeviceId extends Supplier<Long> {}
```
4. a `DeviceId` class that returns an UUID/long
```java
public class DeviceId {
private UUID/long id;

// implement equals and other object methods by returning the UUID/long ones.
}
```

[UUID](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/UUID.html) seems ideal as a type as it's already serializable, comparable, and can easily be generated randomly
```java
UUID.randomUUID()
```

**Comment by smagnaniuni** [comment]
Can you explain with uml/sample code what you mean? Or do you mean option 4?

**Comment by michelececcacci** [comment]
oh right, it's basically option 4.

**Comment by aleemont1** [comment]
Option no. 4 looks good.

**Comment by smagnaniuni** [comment]
@aleemont1 @michelececcacci I have a draft ready, this will probably break the implementations.
How should I make the PR?

**Comment by aleemont1** [comment]
> @aleemont1 @michelececcacci I have a draft ready, this will probably break the implementations.
> How should I make the PR?

Open a draft PR and we'll check that
