### ISSUE TITLE
Use Rebase or Squash and Merge

### ISSUE THREAD

**Issue by aleemont1** [progetto-oop-22-23/HOMER#54]
We shouldn't just merge the PRs with a merge commit, I think it'd be better to rebase or squash and merge. It would be more risky but all commits would appear in history on GitHub. I feel like it'd look more organized and we could see all commits without checking the forks they came from.

@michelececcacci @smagnaniuni what do you think?

**Comment by aleemont1** [comment]
E.g. this doesn't look good.
I think it'd be better for all the commits merged to show directly in history.

![Screenshot_20230304_232214_GitHub.jpg](https://user-images.githubusercontent.com/98494450/222931217-a3faf055-5cb1-4a84-bc93-811557854aab.jpg)

**Comment by smagnaniuni** [comment]
All the commits are still there, the merge commits just represent when they were brought in.
They just don't appear close together because there was some time before the commits and the merge.
Squash and rebase should be done in local.

**Comment by michelececcacci** [comment]
> All the commits are still there, the merge commits just represent when they were brought in. They just don't appear close together because there was some time before the commits and the merge. Squash and rebase should be done in local.

i 100% agree
